# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# csproj Datei unter Ordner-DotNetAppDir kopieren.
WORKDIR /source 
# COPY *.* ./
COPY *.* ./project/
RUN dotnet restore ./project/dotnet.csproj

#Alles in einem Ordner (hier heißt der Ordner "out") bauen.
#Anschließend wird mit dem RUN-Befehl die .NET CLI ausgeführt 
#und mit dem Befehl dotnet publish ein Release-Build 
#im Ordner out veröffentlicht
FROM build AS publish
RUN dotnet publish ./project/dotnet.csproj -c Release -o app

# Einstiegspunkt das dotnet-Programm
WORKDIR /app
#COPY --from=publish /app .
ENTRYPOINT ["dotnet", "dotnet.dll"]